declare const styles: {
  viewport: string;
  enacSistema: string;
  sideNav: string;
  mainPanel: string;
  sideNavBrand: string;
  sideNavLogo: string;
  appHeader: string;
  headerIdentity: string;
  headerMeta: string;
  userAccessBox: string;
  userAccessLabel: string;
  profileAccessField: string;
  environmentBadge: string;
  titleBlock: string;
  appTitle: string;
  contentPanel: string;
  adminNotice: string;
  adminForm: string;
  adminFieldGroup: string;
  active: string;
  metrics: string;
  tutorialPanel: string;
  tutorialHeader: string;
  tutorialGrid: string;
  tutorialCard: string;
  split: string;
  row: string;
  statusChip: string;
  statusSuccess: string;
  statusWarning: string;
  statusDanger: string;
  statusNeutral: string;
};

export default styles;
